import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { collection, query, where, getDocs, orderBy, limit, addDoc, serverTimestamp, updateDoc, doc, deleteDoc } from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from '../firebase';
import { Activity, Flame, Target, Trophy, CheckCircle, Circle, Calendar, Utensils, Loader2, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { generateWorkoutPlan, generateNutritionPlan } from '../lib/gemini';

export const Dashboard = () => {
  const { user, userProfile } = useAuth();
  const [recentWorkouts, setRecentWorkouts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  
  const [activeWorkoutPlan, setActiveWorkoutPlan] = useState<any | null>(null);
  const [activeNutritionPlan, setActiveNutritionPlan] = useState<any | null>(null);

  const generateNewPlan = async () => {
    if (!user || !userProfile) return;
    setGenerating(true);
    try {
      const planDays = 7; // Force 7-day plan as requested
      const wPlan = await generateWorkoutPlan(userProfile.goal || 'general fitness', userProfile.experience_level || 'intermediate', planDays);
      
      const wPlanData = {
        userId: user.uid,
        title: wPlan.title || `${planDays}-Day Workout Plan`,
        description: wPlan.description || 'Generated by AI',
        goal: userProfile.goal || 'general fitness',
        exercises: (wPlan.exercises || []).map((ex: any) => ({
          day: Number(ex.day) || 1,
          name: ex.name || 'Exercise',
          sets: Number(ex.sets) || 3,
          reps: Number(ex.reps) || 10,
          restSeconds: Number(ex.restSeconds) || 60,
          completed: false
        })),
        createdAt: serverTimestamp()
      };
      const wDoc = await addDoc(collection(db, 'workoutPlans'), wPlanData);
      setActiveWorkoutPlan({ id: wDoc.id, ...wPlanData });

      const nPlan = await generateNutritionPlan(
        userProfile.goal || 'maintenance',
        userProfile.weight || 70,
        userProfile.height || 175
      );
      
      const nPlanData = {
        userId: user.uid,
        dailyCalories: Number(nPlan.dailyCalories) || 2000,
        proteinGrams: Number(nPlan.proteinGrams) || 150,
        carbsGrams: Number(nPlan.carbsGrams) || 200,
        fatsGrams: Number(nPlan.fatsGrams) || 70,
        meals: (nPlan.meals || []).map((meal: any) => ({
          name: meal.name || 'Meal',
          description: meal.description || 'Healthy meal',
          calories: Number(meal.calories) || 500,
          protein: Number(meal.protein) || 30,
          carbs: Number(meal.carbs) || 40,
          fats: Number(meal.fats) || 15,
          completed: false
        })),
        lastUpdatedDate: new Date().toISOString().split('T')[0],
        createdAt: serverTimestamp()
      };
      const nDoc = await addDoc(collection(db, 'nutritionPlans'), nPlanData);
      setActiveNutritionPlan({ id: nDoc.id, ...nPlanData });

    } catch (e) {
      console.error("Error generating plan:", e);
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (!user || !userProfile) return;
    
    const fetchStats = async () => {
      try {
        const startOfMonth = new Date();
        startOfMonth.setDate(1);
        startOfMonth.setHours(0, 0, 0, 0);

        const q = query(
          collection(db, 'workoutSessions'),
          where('userId', '==', user.uid),
          where('createdAt', '>=', startOfMonth),
          orderBy('createdAt', 'desc')
        );
        const snapshot = await getDocs(q);
        setRecentWorkouts(snapshot.docs.map(d => ({ id: d.id, ...d.data() })));

        let needsNewPlan = false;

        const qPlan = query(
          collection(db, 'workoutPlans'),
          where('userId', '==', user.uid),
          orderBy('createdAt', 'desc'),
          limit(1)
        );
        const planSnap = await getDocs(qPlan);
        if (!planSnap.empty) {
          const planData = planSnap.docs[0].data();
          const createdAt = planData.createdAt?.toDate ? planData.createdAt.toDate() : new Date(planData.createdAt || Date.now());
          const daysOld = (new Date().getTime() - createdAt.getTime()) / (1000 * 3600 * 24);
          
          if (daysOld >= 7) {
            needsNewPlan = true;
          } else {
            setActiveWorkoutPlan({ id: planSnap.docs[0].id, ...planData });
          }
        } else {
          needsNewPlan = true;
        }

        const qNut = query(
          collection(db, 'nutritionPlans'),
          where('userId', '==', user.uid),
          orderBy('createdAt', 'desc'),
          limit(1)
        );
        const nutSnap = await getDocs(qNut);
        if (!nutSnap.empty && !needsNewPlan) {
          const nutData = nutSnap.docs[0].data();
          const today = new Date().toISOString().split('T')[0];
          let meals = nutData.meals || [];
          let lastUpdatedDate = nutData.lastUpdatedDate;
          
          if (lastUpdatedDate !== today) {
            meals = meals.map((m: any) => ({ ...m, completed: false }));
            await updateDoc(doc(db, 'nutritionPlans', nutSnap.docs[0].id), {
              meals,
              lastUpdatedDate: today
            });
          }
          
          setActiveNutritionPlan({ id: nutSnap.docs[0].id, ...nutData, meals, lastUpdatedDate: today });
        }

        if (needsNewPlan) {
          await generateNewPlan();
        }
      } catch (error) {
        handleFirestoreError(error, OperationType.LIST, 'dashboard_data');
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, [user, userProfile]);

  const toggleExercise = async (index: number) => {
    if (!activeWorkoutPlan || !user || !userProfile) return;
    const updated = [...activeWorkoutPlan.exercises];
    const isNowCompleted = !updated[index].completed;
    updated[index].completed = isNowCompleted;
    
    try {
      if (isNowCompleted) {
        // Automatically log this as a workout session
        const exerciseDetails = updated[index];
        const estimatedDuration = (exerciseDetails.sets * exerciseDetails.reps * 3) + (exerciseDetails.sets * exerciseDetails.restSeconds); // Rough estimate in seconds
        
        const sessionData = {
          userId: user.uid,
          exerciseName: exerciseDetails.name,
          reps: exerciseDetails.sets * exerciseDetails.reps,
          formScore: 0, // Initial form score 0 as requested
          durationSeconds: estimatedDuration,
          createdAt: serverTimestamp()
        };
        
        const docRef = await addDoc(collection(db, 'workoutSessions'), sessionData);
        updated[index].sessionId = docRef.id;
        
        await updateDoc(doc(db, 'workoutPlans', activeWorkoutPlan.id), { exercises: updated });
        setActiveWorkoutPlan({ ...activeWorkoutPlan, exercises: updated });
        
        // Update local state to reflect the new session immediately
        setRecentWorkouts(prev => [{ id: docRef.id, ...sessionData, createdAt: new Date() }, ...prev]);
        
        alert(`Great job completing: ${exerciseDetails.name}! ✅ Calories burned updated.`);
      } else {
        // Remove the workout session
        let sessionId = updated[index].sessionId;
        
        // Fallback if sessionId wasn't saved (e.g., from older completions)
        if (!sessionId) {
          const q = query(
            collection(db, 'workoutSessions'),
            where('userId', '==', user.uid),
            where('exerciseName', '==', updated[index].name),
            orderBy('createdAt', 'desc'),
            limit(1)
          );
          const snap = await getDocs(q);
          if (!snap.empty) {
            sessionId = snap.docs[0].id;
          }
        }
        
        if (sessionId) {
          await deleteDoc(doc(db, 'workoutSessions', sessionId));
          updated[index].sessionId = null;
          setRecentWorkouts(prev => prev.filter(w => w.id !== sessionId));
        }
        
        await updateDoc(doc(db, 'workoutPlans', activeWorkoutPlan.id), { exercises: updated });
        setActiveWorkoutPlan({ ...activeWorkoutPlan, exercises: updated });
      }
    } catch (e) {
      console.error(e);
    }
  };

  const toggleMeal = async (index: number) => {
    if (!activeNutritionPlan) return;
    const updated = [...activeNutritionPlan.meals];
    updated[index].completed = !updated[index].completed;
    
    try {
      const today = new Date().toISOString().split('T')[0];
      await updateDoc(doc(db, 'nutritionPlans', activeNutritionPlan.id), { 
        meals: updated,
        lastUpdatedDate: today
      });
      setActiveNutritionPlan({ ...activeNutritionPlan, meals: updated, lastUpdatedDate: today });
      if (updated[index].completed) {
        alert(`Meal logged: ${updated[index].name}! 🥗`);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const exercisesByDay = activeWorkoutPlan?.exercises?.reduce((acc: any, ex: any, idx: number) => {
    const day = ex.day || 1;
    if (!acc[day]) acc[day] = [];
    acc[day].push({ ...ex, originalIndex: idx });
    return acc;
  }, {});

  const calculateCaloriesBurned = () => {
    if (!userProfile) return 0;
    const weightKg = userProfile.weight || 70;
    const totalMinutes = recentWorkouts.reduce((acc, w) => acc + ((w.durationSeconds || 0) / 60), 0);
    
    let metValue = 5;
    if (userProfile.experience_level === 'advanced') metValue = 8;
    if (userProfile.experience_level === 'beginner') metValue = 4;

    return Math.round(metValue * weightKg * (totalMinutes / 60));
  };

  const caloriesBurned = calculateCaloriesBurned();

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-6"
    >
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-end gap-4">
        <div>
          <h1 className="text-3xl font-bold">Welcome back, {userProfile?.displayName?.split(' ')[0] || 'Athlete'}!</h1>
          <p className="text-zinc-400 mt-1">Ready to crush your goals today?</p>
        </div>
        <div className="flex items-center w-full sm:w-auto">
          {generating ? (
            <div className="flex items-center justify-center w-full sm:w-auto space-x-2 text-indigo-400 bg-indigo-500/10 px-4 py-3 sm:py-2 rounded-xl">
              <Loader2 className="animate-spin" size={20} />
              <span className="font-medium">Generating 7-day plan...</span>
            </div>
          ) : (
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={generateNewPlan}
              className="flex items-center justify-center w-full sm:w-auto space-x-2 bg-gradient-to-r from-indigo-500 to-purple-500 hover:from-indigo-600 hover:to-purple-600 text-white px-4 py-3 sm:py-2 rounded-xl font-medium shadow-lg shadow-indigo-500/25 transition-all"
            >
              <Sparkles size={20} />
              <span>Generate 7-Day Plan</span>
            </motion.button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard icon={Flame} label="Calories Burned" value={caloriesBurned.toLocaleString()} unit="kcal" color="text-orange-500" />
        <StatCard icon={Activity} label="Workouts" value={recentWorkouts.length} unit="this month" color="text-indigo-500" />
        <StatCard icon={Target} label="Current Goal" value={userProfile?.goal?.replace('_', ' ') || 'Set Goal'} unit="" color="text-emerald-500" className="capitalize" />
        <StatCard icon={Trophy} label="Form Score" value={recentWorkouts.length > 0 ? Math.round(recentWorkouts.reduce((acc, w) => acc + (w.formScore || 0), 0) / recentWorkouts.length) : 0} unit="avg" color="text-yellow-500" />
      </div>

      {/* Active Workout Plan */}
      {activeWorkoutPlan && (
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <div className="flex items-center space-x-2 mb-6">
            <Calendar className="text-indigo-500" />
            <h2 className="text-xl font-bold">Your Active Workout Plan</h2>
          </div>
          <div className="space-y-6">
            {Object.keys(exercisesByDay || {}).map(day => (
              <div key={day} className="space-y-3">
                <h3 className="font-bold text-lg text-zinc-300 border-b border-zinc-800 pb-2">Day {day}</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {exercisesByDay[day].map((ex: any) => (
                    <div 
                      key={ex.originalIndex} 
                      onClick={() => toggleExercise(ex.originalIndex)}
                      className={`p-4 rounded-xl border cursor-pointer transition-all flex items-center space-x-4 ${ex.completed ? 'bg-emerald-900/20 border-emerald-800/50' : 'bg-zinc-950 border-zinc-800 hover:border-indigo-500/50'}`}
                    >
                      <div className="shrink-0">
                        {ex.completed ? <CheckCircle className="text-emerald-500" /> : <Circle className="text-zinc-600" />}
                      </div>
                      <div>
                        <p className={`font-medium ${ex.completed ? 'text-emerald-400 line-through opacity-70' : 'text-zinc-100'}`}>{ex.name}</p>
                        <p className="text-sm text-zinc-500">{ex.sets} sets × {ex.reps} reps • {ex.restSeconds}s rest</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Active Nutrition Plan */}
      {activeNutritionPlan && (
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center space-x-2">
              <Utensils className="text-emerald-500" />
              <h2 className="text-xl font-bold">Your Active Diet Plan</h2>
            </div>
          </div>
          
          {/* Daily Macros Summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
            <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-center">
              <p className="text-xs text-zinc-500 uppercase font-medium">Calories</p>
              <p className="text-lg font-bold text-orange-500">
                {activeNutritionPlan.meals?.filter((m: any) => m.completed).reduce((acc: number, m: any) => acc + (m.calories || 0), 0)}
                <span className="text-xs text-zinc-500 font-normal"> / {activeNutritionPlan.dailyCalories}</span>
              </p>
            </div>
            <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-center">
              <p className="text-xs text-zinc-500 uppercase font-medium">Protein</p>
              <p className="text-lg font-bold text-red-500">
                {activeNutritionPlan.meals?.filter((m: any) => m.completed).reduce((acc: number, m: any) => acc + (m.protein || 0), 0)}g
                <span className="text-xs text-zinc-500 font-normal"> / {activeNutritionPlan.proteinGrams}g</span>
              </p>
            </div>
            <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-center">
              <p className="text-xs text-zinc-500 uppercase font-medium">Carbs</p>
              <p className="text-lg font-bold text-blue-500">
                {activeNutritionPlan.meals?.filter((m: any) => m.completed).reduce((acc: number, m: any) => acc + (m.carbs || 0), 0)}g
                <span className="text-xs text-zinc-500 font-normal"> / {activeNutritionPlan.carbsGrams}g</span>
              </p>
            </div>
            <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-3 text-center">
              <p className="text-xs text-zinc-500 uppercase font-medium">Fats</p>
              <p className="text-lg font-bold text-yellow-500">
                {activeNutritionPlan.meals?.filter((m: any) => m.completed).reduce((acc: number, m: any) => acc + (m.fats || 0), 0)}g
                <span className="text-xs text-zinc-500 font-normal"> / {activeNutritionPlan.fatsGrams}g</span>
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {activeNutritionPlan.meals?.map((meal: any, idx: number) => (
              <div 
                key={idx} 
                onClick={() => toggleMeal(idx)}
                className={`p-4 rounded-xl border cursor-pointer transition-all flex items-center space-x-4 ${meal.completed ? 'bg-emerald-900/20 border-emerald-800/50' : 'bg-zinc-950 border-zinc-800 hover:border-emerald-500/50'}`}
              >
                <div className="shrink-0">
                  {meal.completed ? <CheckCircle className="text-emerald-500" /> : <Circle className="text-zinc-600" />}
                </div>
                <div className="flex-1">
                  <p className={`font-medium ${meal.completed ? 'text-emerald-400 line-through opacity-70' : 'text-zinc-100'}`}>{meal.name}</p>
                  <p className="text-sm text-zinc-400 mb-2">{meal.description}</p>
                  <div className="flex flex-wrap gap-2 mt-1">
                    <span className="text-xs font-medium text-orange-400 bg-orange-400/10 px-2 py-1 rounded-md">{meal.calories} kcal</span>
                    <span className="text-xs font-medium text-red-400 bg-red-400/10 px-2 py-1 rounded-md">{meal.protein || 0}g Protein</span>
                    <span className="text-xs font-medium text-blue-400 bg-blue-400/10 px-2 py-1 rounded-md">{meal.carbs || 0}g Carbs</span>
                    <span className="text-xs font-medium text-yellow-400 bg-yellow-400/10 px-2 py-1 rounded-md">{meal.fats || 0}g Fats</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
        <h2 className="text-xl font-bold mb-4">Recent Activity</h2>
        {loading ? (
          <div className="animate-pulse space-y-4">
            {[1, 2, 3].map(i => <div key={i} className="h-16 bg-zinc-800 rounded-xl" />)}
          </div>
        ) : recentWorkouts.length > 0 ? (
          <div className="space-y-4">
            {recentWorkouts.slice(0, 5).map(workout => (
              <div key={workout.id} className="flex items-center justify-between p-4 bg-zinc-950 rounded-xl border border-zinc-800">
                <div>
                  <p className="font-medium">{workout.exerciseName}</p>
                  <p className="text-sm text-zinc-400">
                    {workout.createdAt?.toDate ? workout.createdAt.toDate().toLocaleDateString() : new Date(workout.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="text-right">
                  <p className="font-bold">{workout.reps} reps</p>
                  <p className="text-sm text-emerald-400">Score: {workout.formScore}</p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-zinc-400">No recent workouts found. Time to hit the gym!</p>
        )}
      </div>

      {/* Modal removed */}
    </motion.div>
  );
};

const StatCard = ({ icon: Icon, label, value, unit, color, className = '' }: any) => (
  <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 flex items-start space-x-4">
    <div className={`p-3 rounded-xl bg-zinc-950 border border-zinc-800 ${color}`}>
      <Icon size={24} />
    </div>
    <div>
      <p className="text-zinc-400 text-sm font-medium">{label}</p>
      <p className={`text-2xl font-bold mt-1 ${className}`}>
        {value} <span className="text-sm font-normal text-zinc-500">{unit}</span>
      </p>
    </div>
  </div>
);
