import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { collection, query, where, getDocs, orderBy, limit, addDoc, serverTimestamp, updateDoc, doc } from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from '../firebase';
import { Activity, Flame, Target, Trophy, X, CheckCircle, Circle, Calendar, Utensils } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { generateWorkoutPlan, generateNutritionPlan } from '../lib/gemini';

export const Dashboard = () => {
  const { user, userProfile } = useAuth();
  const [recentWorkouts, setRecentWorkouts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  
  const [activeWorkoutPlan, setActiveWorkoutPlan] = useState<any | null>(null);
  const [activeNutritionPlan, setActiveNutritionPlan] = useState<any | null>(null);
  
  const [showConfigModal, setShowConfigModal] = useState(false);
  const [planDays, setPlanDays] = useState(3);
  const [includeDiet, setIncludeDiet] = useState(false);

  useEffect(() => {
    if (!user) return;
    const fetchStats = async () => {
      try {
        const q = query(
          collection(db, 'workoutSessions'),
          where('userId', '==', user.uid),
          orderBy('createdAt', 'desc'),
          limit(5)
        );
        const snapshot = await getDocs(q);
        setRecentWorkouts(snapshot.docs.map(d => ({ id: d.id, ...d.data() })));

        const qPlan = query(
          collection(db, 'workoutPlans'),
          where('userId', '==', user.uid),
          orderBy('createdAt', 'desc'),
          limit(1)
        );
        const planSnap = await getDocs(qPlan);
        if (!planSnap.empty) {
          setActiveWorkoutPlan({ id: planSnap.docs[0].id, ...planSnap.docs[0].data() });
        }

        const qNut = query(
          collection(db, 'nutritionPlans'),
          where('userId', '==', user.uid),
          orderBy('createdAt', 'desc'),
          limit(1)
        );
        const nutSnap = await getDocs(qNut);
        if (!nutSnap.empty) {
          setActiveNutritionPlan({ id: nutSnap.docs[0].id, ...nutSnap.docs[0].data() });
        }
      } catch (error) {
        handleFirestoreError(error, OperationType.LIST, 'dashboard_data');
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, [user]);

  const handleGenerateSubmit = async () => {
    if (!user) return;
    setGenerating(true);
    try {
      const wPlan = await generateWorkoutPlan(userProfile?.goal || 'general fitness', 'intermediate', planDays);
      
      const wPlanData = {
        userId: user.uid,
        title: wPlan.title || `${planDays}-Day Workout Plan`,
        description: wPlan.description || 'Generated by AI',
        goal: userProfile?.goal || 'general fitness',
        exercises: (wPlan.exercises || []).map((ex: any) => ({
          day: ex.day || 1,
          name: ex.name || 'Exercise',
          sets: ex.sets || 3,
          reps: ex.reps || 10,
          restSeconds: ex.restSeconds || 60,
          completed: false
        })),
        createdAt: serverTimestamp()
      };
      const wDoc = await addDoc(collection(db, 'workoutPlans'), wPlanData);
      setActiveWorkoutPlan({ id: wDoc.id, ...wPlanData });

      if (includeDiet) {
        const nPlan = await generateNutritionPlan(
          userProfile?.goal || 'maintenance',
          userProfile?.weight || 70,
          userProfile?.height || 175
        );
        
        const nPlanData = {
          userId: user.uid,
          dailyCalories: nPlan.dailyCalories || 2000,
          proteinGrams: nPlan.proteinGrams || 150,
          carbsGrams: nPlan.carbsGrams || 200,
          fatsGrams: nPlan.fatsGrams || 70,
          meals: (nPlan.meals || []).map((meal: any) => ({
            name: meal.name || 'Meal',
            description: meal.description || 'Healthy meal',
            calories: meal.calories || 500,
            completed: false
          })),
          createdAt: serverTimestamp()
        };
        const nDoc = await addDoc(collection(db, 'nutritionPlans'), nPlanData);
        setActiveNutritionPlan({ id: nDoc.id, ...nPlanData });
      }

      setShowConfigModal(false);
      alert('New plan generated successfully! 🎉');
    } catch (e) {
      console.error("Error generating plan:", e);
      try {
        handleFirestoreError(e, OperationType.CREATE, 'plans');
      } catch (err) {
        // Ignore thrown error
      }
    } finally {
      setGenerating(false);
    }
  };

  const toggleExercise = async (index: number) => {
    if (!activeWorkoutPlan) return;
    const updated = [...activeWorkoutPlan.exercises];
    updated[index].completed = !updated[index].completed;
    
    try {
      await updateDoc(doc(db, 'workoutPlans', activeWorkoutPlan.id), { exercises: updated });
      setActiveWorkoutPlan({ ...activeWorkoutPlan, exercises: updated });
      if (updated[index].completed) {
        alert(`Great job completing: ${updated[index].name}! ✅`);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const toggleMeal = async (index: number) => {
    if (!activeNutritionPlan) return;
    const updated = [...activeNutritionPlan.meals];
    updated[index].completed = !updated[index].completed;
    
    try {
      await updateDoc(doc(db, 'nutritionPlans', activeNutritionPlan.id), { meals: updated });
      setActiveNutritionPlan({ ...activeNutritionPlan, meals: updated });
      if (updated[index].completed) {
        alert(`Meal logged: ${updated[index].name}! 🥗`);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const exercisesByDay = activeWorkoutPlan?.exercises?.reduce((acc: any, ex: any, idx: number) => {
    const day = ex.day || 1;
    if (!acc[day]) acc[day] = [];
    acc[day].push({ ...ex, originalIndex: idx });
    return acc;
  }, {});

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-6"
    >
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold">Welcome back, {userProfile?.displayName?.split(' ')[0] || 'Athlete'}!</h1>
          <p className="text-zinc-400 mt-1">Ready to crush your goals today?</p>
        </div>
        <button 
          onClick={() => setShowConfigModal(true)}
          className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-xl font-medium transition-colors"
        >
          Generate New Plan
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard icon={Flame} label="Calories Burned" value="2,450" unit="kcal" color="text-orange-500" />
        <StatCard icon={Activity} label="Workouts" value="12" unit="this month" color="text-indigo-500" />
        <StatCard icon={Target} label="Current Goal" value={userProfile?.goal?.replace('_', ' ') || 'Set Goal'} unit="" color="text-emerald-500" className="capitalize" />
        <StatCard icon={Trophy} label="Form Score" value="94" unit="avg" color="text-yellow-500" />
      </div>

      {/* Active Workout Plan */}
      {activeWorkoutPlan && (
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <div className="flex items-center space-x-2 mb-6">
            <Calendar className="text-indigo-500" />
            <h2 className="text-xl font-bold">Your Active Workout Plan</h2>
          </div>
          <div className="space-y-6">
            {Object.keys(exercisesByDay || {}).map(day => (
              <div key={day} className="space-y-3">
                <h3 className="font-bold text-lg text-zinc-300 border-b border-zinc-800 pb-2">Day {day}</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {exercisesByDay[day].map((ex: any) => (
                    <div 
                      key={ex.originalIndex} 
                      onClick={() => toggleExercise(ex.originalIndex)}
                      className={`p-4 rounded-xl border cursor-pointer transition-all flex items-center space-x-4 ${ex.completed ? 'bg-emerald-900/20 border-emerald-800/50' : 'bg-zinc-950 border-zinc-800 hover:border-indigo-500/50'}`}
                    >
                      <div className="shrink-0">
                        {ex.completed ? <CheckCircle className="text-emerald-500" /> : <Circle className="text-zinc-600" />}
                      </div>
                      <div>
                        <p className={`font-medium ${ex.completed ? 'text-emerald-400 line-through opacity-70' : 'text-zinc-100'}`}>{ex.name}</p>
                        <p className="text-sm text-zinc-500">{ex.sets} sets × {ex.reps} reps • {ex.restSeconds}s rest</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Active Nutrition Plan */}
      {activeNutritionPlan && (
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
          <div className="flex items-center space-x-2 mb-6">
            <Utensils className="text-emerald-500" />
            <h2 className="text-xl font-bold">Your Active Diet Plan</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {activeNutritionPlan.meals?.map((meal: any, idx: number) => (
              <div 
                key={idx} 
                onClick={() => toggleMeal(idx)}
                className={`p-4 rounded-xl border cursor-pointer transition-all flex items-center space-x-4 ${meal.completed ? 'bg-emerald-900/20 border-emerald-800/50' : 'bg-zinc-950 border-zinc-800 hover:border-emerald-500/50'}`}
              >
                <div className="shrink-0">
                  {meal.completed ? <CheckCircle className="text-emerald-500" /> : <Circle className="text-zinc-600" />}
                </div>
                <div>
                  <p className={`font-medium ${meal.completed ? 'text-emerald-400 line-through opacity-70' : 'text-zinc-100'}`}>{meal.name}</p>
                  <p className="text-sm text-zinc-500">{meal.calories} kcal • {meal.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
        <h2 className="text-xl font-bold mb-4">Recent Activity</h2>
        {loading ? (
          <div className="animate-pulse space-y-4">
            {[1, 2, 3].map(i => <div key={i} className="h-16 bg-zinc-800 rounded-xl" />)}
          </div>
        ) : recentWorkouts.length > 0 ? (
          <div className="space-y-4">
            {recentWorkouts.map(workout => (
              <div key={workout.id} className="flex items-center justify-between p-4 bg-zinc-950 rounded-xl border border-zinc-800">
                <div>
                  <p className="font-medium">{workout.exerciseName}</p>
                  <p className="text-sm text-zinc-400">
                    {workout.createdAt?.toDate ? workout.createdAt.toDate().toLocaleDateString() : new Date(workout.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="text-right">
                  <p className="font-bold">{workout.reps} reps</p>
                  <p className="text-sm text-emerald-400">Score: {workout.formScore}</p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-zinc-400">No recent workouts found. Time to hit the gym!</p>
        )}
      </div>

      <AnimatePresence>
        {showConfigModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 max-w-md w-full"
            >
              <div className="flex justify-between items-start mb-6">
                <h2 className="text-2xl font-bold text-white">Configure New Plan</h2>
                <button onClick={() => setShowConfigModal(false)} className="p-2 hover:bg-zinc-800 rounded-full transition-colors">
                  <X size={20} />
                </button>
              </div>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-zinc-400 mb-2">Number of Days</label>
                  <input 
                    type="number" 
                    min="1" 
                    max="7" 
                    value={planDays}
                    onChange={(e) => setPlanDays(parseInt(e.target.value) || 1)}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-indigo-500"
                  />
                </div>
                
                <label className="flex items-center space-x-3 cursor-pointer p-4 bg-zinc-950 border border-zinc-800 rounded-xl hover:border-zinc-700 transition-colors">
                  <input 
                    type="checkbox" 
                    checked={includeDiet}
                    onChange={(e) => setIncludeDiet(e.target.checked)}
                    className="w-5 h-5 rounded border-zinc-700 text-indigo-600 focus:ring-indigo-500 bg-zinc-900"
                  />
                  <div>
                    <p className="font-medium text-white">Include Diet Plan</p>
                    <p className="text-sm text-zinc-500">Generate a matching nutrition plan</p>
                  </div>
                </label>
              </div>

              <button 
                onClick={handleGenerateSubmit}
                disabled={generating}
                className="w-full mt-6 bg-indigo-600 hover:bg-indigo-700 text-white py-3 rounded-xl font-bold transition-colors disabled:opacity-50 flex justify-center items-center"
              >
                {generating ? 'Generating...' : 'Generate Plan'}
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const StatCard = ({ icon: Icon, label, value, unit, color, className = '' }: any) => (
  <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 flex items-start space-x-4">
    <div className={`p-3 rounded-xl bg-zinc-950 border border-zinc-800 ${color}`}>
      <Icon size={24} />
    </div>
    <div>
      <p className="text-zinc-400 text-sm font-medium">{label}</p>
      <p className={`text-2xl font-bold mt-1 ${className}`}>
        {value} <span className="text-sm font-normal text-zinc-500">{unit}</span>
      </p>
    </div>
  </div>
);
